# Generated by Django 4.1.1 on 2022-10-18 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dosen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NIP', models.CharField(max_length=200)),
                ('nama', models.CharField(max_length=200)),
                ('NIDN', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('jabatan', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Fasilitas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sarana', models.CharField(max_length=200)),
                ('unit', models.CharField(max_length=200)),
                ('kualitas', models.CharField(max_length=200)),
                ('pengelola', models.CharField(max_length=200)),
            ],
        ),
    ]
